services:
  app:
    container_name: laravel-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:80"
    volumes:
      - ./storage:/var/www/html/storage
    environment:
      - APP_ENV=${APP_ENV:-local}
      - APP_DEBUG=${APP_DEBUG:-true}
      - APP_KEY=${APP_KEY}
      - APP_URL=${APP_URL:-http://localhost:8000}
      - DB_CONNECTION=${DB_CONNECTION:-mysql}
      - DB_HOST=${DB_HOST:-host.docker.internal}
      - DB_PORT=${DB_PORT:-3306}
      - DB_DATABASE=${DB_DATABASE:-lowiska}
      - DB_USERNAME=${DB_USERNAME:-root}
      - DB_PASSWORD=${DB_PASSWORD:-}
      - CACHE_STORE=${CACHE_STORE:-database}
      - SESSION_DRIVER=${SESSION_DRIVER:-database}
      - QUEUE_CONNECTION=${QUEUE_CONNECTION:-database}
    extra_hosts:
      - "mysql-host:192.168.65.7"
    networks:
      - laravel

  queue:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./storage:/var/www/html/storage
    environment:
      - APP_ENV=${APP_ENV:-local}
      - APP_DEBUG=${APP_DEBUG:-true}
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=${DB_CONNECTION:-mysql}
      - DB_HOST=${DB_HOST:-host.docker.internal}
      - DB_PORT=${DB_PORT:-3306}
      - DB_DATABASE=${DB_DATABASE:-lowiska}
      - DB_USERNAME=${DB_USERNAME:-root}
      - DB_PASSWORD=${DB_PASSWORD:-}
      - CACHE_STORE=${CACHE_STORE:-database}
      - SESSION_DRIVER=${SESSION_DRIVER:-database}
      - QUEUE_CONNECTION=${QUEUE_CONNECTION:-database}
    command: php artisan queue:work --verbose --tries=3 --timeout=90
    extra_hosts:
      - "mysql-host:192.168.65.7"
    networks:
      - laravel

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./storage:/var/www/html/storage
    environment:
      - APP_ENV=${APP_ENV:-local}
      - APP_DEBUG=${APP_DEBUG:-true}
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=${DB_CONNECTION:-mysql}
      - DB_HOST=${DB_HOST:-host.docker.internal}
      - DB_PORT=${DB_PORT:-3306}
      - DB_DATABASE=${DB_DATABASE:-lowiska}
      - DB_USERNAME=${DB_USERNAME:-root}
      - DB_PASSWORD=${DB_PASSWORD:-}
      - CACHE_STORE=${CACHE_STORE:-database}
      - SESSION_DRIVER=${SESSION_DRIVER:-database}
      - QUEUE_CONNECTION=${QUEUE_CONNECTION:-database}
    command: >
      bash -c "while true; do
        php artisan schedule:run;
        sleep 60;
      done"
    extra_hosts:
      - "mysql-host:192.168.65.7"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge