<?php

namespace Tests\Feature;

use Illuminate\Support\Facades\Artisan;
use Spatie\Permission\Models\Permission;

/**
 * Regresja dla zadania 009 (upgrade Shielda 3.x → 4.x).
 *
 * Shield 4 zmienił format kluczy uprawnień (`view_any_fishery::type` →
 * `view_any:fishery_type`) i formatu 3.x nie da się odtworzyć konfiguracją.
 * Polityki w app/Policies/ pytają o uprawnienia po nazwie, więc rozjazd między
 * tym, co polityka sprawdza, a tym, co generator Shielda tworzy, odbiera dostęp
 * do wszystkiego — po cichu.
 *
 * ⚠️ Zwykły pakiet testów tego NIE złapie: tests/TestCase.php zakłada uprawnienia
 * RĘCZNIE, z listy literałów, więc panele świecą na zielono nawet wtedy, gdy
 * generator produkuje zupełnie inne nazwy. Ten test jest jedynym miejscem, które
 * porównuje polityki z FAKTYCZNYM wynikiem `shield:generate`.
 */
test('every permission referenced by a policy is actually generated by Shield', function () {
    foreach (['admin', 'owner'] as $panel) {
        Artisan::call('shield:generate', [
            '--panel' => $panel,
            '--option' => 'permissions',
            '--all' => true,
            '--silent' => true,
        ]);
    }

    $generated = Permission::pluck('name')->all();

    expect($generated)->not->toBeEmpty();

    $policyFiles = glob(app_path('Policies/*.php'));
    expect($policyFiles)->not->toBeEmpty();

    $referenced = [];

    foreach ($policyFiles as $file) {
        preg_match_all(
            "/'([a-z_]+:[a-z_]+)'/",
            (string) file_get_contents($file),
            $matches
        );

        foreach ($matches[1] as $permission) {
            $referenced[$permission][] = basename($file);
        }
    }

    expect($referenced)->not->toBeEmpty();

    $missing = [];

    foreach ($referenced as $permission => $files) {
        if (! in_array($permission, $generated, true)) {
            $missing[] = $permission.' ('.implode(', ', array_unique($files)).')';
        }
    }

    expect($missing)->toBe(
        [],
        "Polityki pytają o uprawnienia, których shield:generate nie tworzy:\n".implode("\n", $missing)
    );
});
